### PR TITLE
Use though2 and other clean up for newer Node versions

### PR DESCRIPTION
**Pull request by mourner**
@maxogden given that this module is awesome and very useful but wasn't updated for almost 2 years, I thought I'd give it a minor update. :)

- switched to though2 to ensure everything works on newer Node versions and has benefits of streams2
- added standard since I noticed that you use it for your modules now
- made sure tests pass on Node 5, 0.12 and 0.10

Let me know if there's anything else to do here before you can merge and push a new version to NPM.

### CODE REVIEW

**Comment by mourner** [comment]
Probably worth hooking up to Travis too. And maybe doing some benchmarks against the current version.

**Comment by maxogden** [comment]
@mourner HI!!! awesome PR :)

**Comment by maxogden** [comment]
published 1.0.0, added travis, added you as a collaborator (http://openopensource.org/ style). thanks for the PR!

**Comment by mourner** [comment]
Awesome, thanks a lot Max! Was just going to suggest hooking up Travis too. :)
BTW, we're using the module in this thing: https://www.mapbox.com/blog/tile-reduce-3/

**Pull request merged**
