### PR TITLE
Turn on object mode for the readable side

### LINKED ISSUE #12: Streams2 interface not splitting correctly?
I was just writing some one off scripts and used this to split stdin -- only to find that I was getting combined data from the source. I suspect this might be an artifact of using through2 and possibly not setting the readable portion of the stream in object mode to guarantee one push = one readable chunk.

`foo`:
```
/volume1/data/keke
/volume1/data/lar
/volume1/dufus
```

`test.js`:
```js
'use strict';

var split = require('binary-split'),
    fs = require('fs');

var stream = fs.createReadStream('./foo').pipe(split());

setTimeout(function () {
    console.log(stream.read().toString());
}, 500);
```

output:
```
admin@ds:~/merge-dirs$ node test
/volume1/data/keke/volume1/data/lar/volume1/dufus
```

```
admin@ds:~/merge-dirs$ node -v
v4.4.2
```

### PR DESCRIPTION
**Pull request by mourner**
Fixes #12 (better late than never!). Also has a nice side effect of ~8% performance improvement. 

I assume this would warrant a major version bump just to be on the safe side?

### CODE REVIEW

**Comment by mourner** [comment]
@cc @tyrasd @myndzi thoughts?

**Comment by myndzi** [comment]
Seems to do the thing. I still have a difference in behavior with my tests regarding empty tokens and empty delimiters primarily; for example, with the input `"abcde"` and a delimiter of `""`, I emit `["a", "b", "c", "d", "e"]`, while this package seems to emit `"abcde"`.  This could be seen as a behavioral choice and not a bug, but diverges from `String.prototype.split`. Equally, my code emits empty values in the case of an input such as `"abba"` with a delimiter of `"b"`: `["a", "", "a"]`, while this code emits `["a", "a"]`. Same thing. Neither really affects this PR, but they do block the PR I was originally preparing when filing #12 (which was to integrate my test suite into this package).

**Comment by myndzi** [comment]
(If you're interested, the WIP branch is here: https://github.com/myndzi/binary-split/tree/integrate-new-tests -- I didn't bother to convert the test runner yet since the tests simply fail)

**Comment by mourner** [comment]
@myndzi good points! I think we should follow the same logic for edge cases as `split` and `split2` packages — let's check how those behave.

**Comment by mourner** [comment]
@myndzi results for `split2` are mixed:

- `'.a..b.'` / `'.'` -> `['', 'a', '', 'b']`
- `'abcd'` / `''` -> `['abcd']`

**Pull request merged**
